from __future__ import annotations

from app.models import AiSuggestion, Category, Severity, Status

STUDIES = [
    {"code": "ST-104", "name": "HARMONY NSCLC"},
    {"code": "ST-221", "name": "RIVER Heart Failure"},
    {"code": "ST-018", "name": "LARK RSV Vaccine"},
]

SITES = [
    {"study_code": "ST-104", "code": "01", "name": "Metro General"},
    {"study_code": "ST-104", "code": "04", "name": "Lakeside Research"},
    {"study_code": "ST-104", "code": "12", "name": "North Clinic"},
    {"study_code": "ST-221", "code": "02", "name": "Harbor Medical"},
    {"study_code": "ST-221", "code": "07", "name": "Valley Site"},
    {"study_code": "ST-018", "code": "03", "name": "Ridgeview"},
]

ISSUES: list[dict] = [
    dict(
        study_code="ST-104",
        site_code="01",
        created=-6,
        status=Status.OPEN,
        owner="Site manager",
        category=Category.SAFETY_REPORTING,
        severity=Severity.CRITICAL,
        description="The 24-hour sponsor notification for a serious adverse event identified at last week's visit was not sent. The reporting clock is already past due.",
        summary="Missed 24-hour SAE notification clock at Metro General.",
        recommended_action="Send the outstanding sponsor notification now, document the clock start/stop, and confirm IRB reporting status. Do not assess causality.",
        ai=AiSuggestion(
            category=Category.SAFETY_REPORTING,
            severity=Severity.CRITICAL,
            summary="Missed 24-hour SAE notification clock at Metro General.",
            recommended_action="Send the outstanding sponsor notification now, document the clock start/stop, and confirm IRB reporting status. Do not assess causality.",
            rationale="A missed safety reporting deadline is critical operational impact.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-104",
        site_code="04",
        created=-3,
        status=Status.IN_PROGRESS,
        owner="Pharmacy",
        category=Category.IP_MANAGEMENT,
        severity=Severity.HIGH,
        description="Pharmacy documented a temperature excursion on the investigational product refrigerator overnight. Kits on the affected shelf have not been quarantined in the IRT.",
        summary="IP refrigerator excursion; kits not yet quarantined in IRT.",
        recommended_action="Quarantine affected kits in IRT, keep them out of dispensing, and notify pharmacy and the sponsor per the pharmacy manual.",
        ai=AiSuggestion(
            category=Category.IP_MANAGEMENT,
            severity=Severity.HIGH,
            summary="IP refrigerator excursion; kits not yet quarantined in IRT.",
            recommended_action="Quarantine affected kits in IRT, keep them out of dispensing, and notify pharmacy and the sponsor per the pharmacy manual.",
            rationale="IP accountability gaps threaten supply and compliance if not fixed soon.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-221",
        site_code="02",
        created=-4,
        status=Status.OPEN,
        owner="CRC",
        category=Category.CONSENT,
        severity=Severity.HIGH,
        description="Two screenings this week used consent version 3.0 after IRB approved version 4.1. The current version is in the regulatory binder but was not placed in the visit kits.",
        summary="Screenings used expired consent version 3.0 instead of 4.1.",
        recommended_action="Stop using version 3.0, reconsent with 4.1 if required, and replace visit-kit copies.",
        ai=AiSuggestion(
            category=Category.CONSENT,
            severity=Severity.MEDIUM,
            summary="Wrong consent version used at screening.",
            recommended_action="Replace the form in the kit and reconsent if required.",
            rationale="Consent version mismatch is usually a contained process gap.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-104",
        site_code="12",
        created=-8,
        status=Status.OPEN,
        owner=None,
        category=Category.PROTOCOL_DEVIATION,
        severity=Severity.MEDIUM,
        description="Week 8 visits for two participants were completed three days outside the protocol window. The PI has not yet signed the deviation forms.",
        summary="Two Week 8 visits completed outside the protocol window.",
        recommended_action="Complete deviation forms, obtain PI signature, and file per the site deviation SOP.",
        ai=AiSuggestion(
            category=Category.PROTOCOL_DEVIATION,
            severity=Severity.MEDIUM,
            summary="Two Week 8 visits completed outside the protocol window.",
            recommended_action="Complete deviation forms, obtain PI signature, and file per the site deviation SOP.",
            rationale="Out-of-window visits are a contained protocol process gap.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-018",
        site_code="03",
        created=-10,
        status=Status.ESCALATED,
        owner="Regulatory",
        category=Category.REGULATORY_IRB,
        severity=Severity.HIGH,
        description="Continuing review acknowledgement from the IRB is not in the binder and expires in four days. The coordinator has not received the approval letter.",
        summary="IRB continuing review acknowledgement missing; expiry in four days.",
        recommended_action="Obtain the IRB acknowledgement, file it, and confirm coverage before visits that depend on it.",
        ai=AiSuggestion(
            category=Category.REGULATORY_IRB,
            severity=Severity.HIGH,
            summary="IRB continuing review acknowledgement missing; expiry in four days.",
            recommended_action="Obtain the IRB acknowledgement, file it, and confirm coverage before visits that depend on it.",
            rationale="An approaching IRB expiry threatens compliance if not closed soon.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-221",
        site_code="07",
        created=-2,
        status=Status.OPEN,
        owner="Data manager",
        category=Category.DATA_QUALITY,
        severity=Severity.HIGH,
        description="Thirty-two open queries are aging past 14 days, including several source-to-CRF mismatches on primary endpoint pages before Friday's data cut.",
        summary="32 queries aging past 14 days ahead of Friday data cut.",
        recommended_action="Prioritize endpoint-page queries, assign owners, and close them before the data cut.",
        ai=AiSuggestion(
            category=Category.DATA_QUALITY,
            severity=Severity.HIGH,
            summary="32 queries aging past 14 days ahead of Friday data cut.",
            recommended_action="Prioritize endpoint-page queries, assign owners, and close them before the data cut.",
            rationale="Unresolved endpoint queries threaten data integrity before a cut.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-104",
        site_code="01",
        created=-1,
        status=Status.OPEN,
        owner="CRC",
        category=Category.ENROLLMENT,
        severity=Severity.MEDIUM,
        description="The screening log is missing outcomes for last Thursday's pre-screens, so the site cannot confirm which patients are still pending eligibility review.",
        summary="Screening log missing Thursday pre-screen outcomes.",
        recommended_action="Backfill the screening log and confirm pending eligibility with the PI before the next slot.",
        ai=AiSuggestion(
            category=Category.ENROLLMENT,
            severity=Severity.MEDIUM,
            summary="Screening log missing Thursday pre-screen outcomes.",
            recommended_action="Backfill the screening log and confirm pending eligibility with the PI before the next slot.",
            rationale="Log gaps are a contained enrollment process issue.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-018",
        site_code="03",
        created=-12,
        status=Status.OPEN,
        owner="Lab",
        category=Category.EQUIPMENT_LAB,
        severity=Severity.MEDIUM,
        description="The backup freezer alarm was silenced during a weekend power blip. Calibration is current, but the incident was not logged and staff are unsure whether samples were moved.",
        summary="Backup freezer alarm silenced; weekend incident not logged.",
        recommended_action="Log the incident, confirm sample location, and restore alarm settings.",
        ai=AiSuggestion(
            category=Category.EQUIPMENT_LAB,
            severity=Severity.MEDIUM,
            summary="Backup freezer alarm silenced; weekend incident not logged.",
            recommended_action="Log the incident, confirm sample location, and restore alarm settings.",
            rationale="Equipment process gap appears contained.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-221",
        site_code="02",
        created=-5,
        status=Status.IN_PROGRESS,
        owner="CRA",
        category=Category.MONITORING_FINDING,
        severity=Severity.MEDIUM,
        description="The last monitoring letter asked for certified copies of three source notes that are still not in the eTMF. Response is due this week.",
        summary="Monitoring letter: three certified source copies still outstanding.",
        recommended_action="Upload the certified copies and send the site response before the letter due date.",
        ai=AiSuggestion(
            category=Category.MONITORING_FINDING,
            severity=Severity.MEDIUM,
            summary="Monitoring letter: three certified source copies still outstanding.",
            recommended_action="Upload the certified copies and send the site response before the letter due date.",
            rationale="Open monitoring follow-up is a contained process gap.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-104",
        site_code="04",
        created=-15,
        resolved=-2,
        status=Status.RESOLVED,
        owner="Site manager",
        category=Category.STAFFING_TRAINING,
        severity=Severity.MEDIUM,
        resolution_note="Coordinator completed protocol training; delegation log updated 15 Sep. No untrained staff assigned to visits.",
        description="A newly hired coordinator was listed on the visit calendar before protocol-specific training and delegation were complete.",
        summary="New coordinator scheduled before training and delegation were complete.",
        recommended_action="Remove untrained staff from the calendar, complete training, and update the delegation log.",
        ai=AiSuggestion(
            category=Category.STAFFING_TRAINING,
            severity=Severity.MEDIUM,
            summary="New coordinator scheduled before training and delegation were complete.",
            recommended_action="Remove untrained staff from the calendar, complete training, and update the delegation log.",
            rationale="Training/delegation gaps are contained if visits have not started.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-018",
        site_code="03",
        created=-20,
        resolved=-6,
        status=Status.RESOLVED,
        owner="Finance",
        category=Category.CONTRACT_BUDGET,
        severity=Severity.LOW,
        resolution_note="Invoice #4412 resubmitted with the correct visit codes; AP confirmed receipt.",
        description="The last visit invoice was rejected because visit codes did not match the budget grid. No subject visits are blocked.",
        summary="Visit invoice rejected for mismatched budget grid codes.",
        recommended_action="Correct the visit codes and resubmit the invoice to AP.",
        ai=AiSuggestion(
            category=Category.CONTRACT_BUDGET,
            severity=Severity.LOW,
            summary="Visit invoice rejected for mismatched budget grid codes.",
            recommended_action="Correct the visit codes and resubmit the invoice to AP.",
            rationale="Administrative payment issue with no visit impact.",
            phi_flag=False,
        ),
    ),
    dict(
        study_code="ST-221",
        site_code="07",
        created=-1,
        status=Status.OPEN,
        owner=None,
        category=Category.OTHER,
        severity=Severity.LOW,
        description="The copier used for certified copies is down. Staff are using the clinic copier on another floor until repair.",
        summary="Certified-copy copier is down; staff using another floor.",
        recommended_action="Use the clinic copier for certified copies until repair, and log the workaround.",
        ai=None,
    ),
]
